# Generated by Django 4.2.5 on 2023-09-07 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color_variant',
            field=models.ForeignKey(default='Unknown', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_variant', to='products.colorvariant'),
        ),
    ]
