# Generated by Django 4.2.5 on 2023-09-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='ProfileImages/default_pp.jpg', upload_to='ProfileImages'),
        ),
    ]
